
'use strict';
const RUBRICS=[
{name:'Exposición',items:[['Dominio del tema',3],['Claridad y expresión oral',3],['Organización de las ideas',2],['Uso de recursos y actitud',2]]},
{name:'Cuaderno',items:[['Actividades completas',5],['Organización y secuencia',4],['Limpieza y presentación',3],['Corrección de actividades',4],['Responsabilidad',4]]},
{name:'Evaluación / Examen',items:[['Comprensión de conceptos',6],['Aplicación de aprendizajes',6],['Resolución de ejercicios',5],['Organización y presentación',3]]},
{name:'Proyecto final',items:[['Comprensión del tema',3],['Creatividad',2],['Cumplimiento de instrucciones',2],['Presentación del trabajo',2],['Entrega y responsabilidad',1]]},
{name:'Participación',items:[['Participación voluntaria',4],['Preguntas y respuestas',3],['Comprensión',3],['Respeto de turnos y opiniones',3],['Interés y atención',2]]},
{name:'Práctica',items:[['Comprensión de instrucciones',3],['Realización de actividades',5],['Aplicación de conocimientos',3],['Trabajo colaborativo',2],['Orden y cumplimiento',2]]},
{name:'Asistencia',items:[['Asistencia regular',4],['Puntualidad',2],['Justificación de ausencias',2],['Constancia durante el período',2]]}
];
const IND=RUBRICS.flatMap(r=>r.items.map(([label,max])=>({id:r.name+'::'+label,label,max,group:r.name})));
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={db:null,user:null,students:[],subjects:[],periods:[],enrollments:[],evaluations:[],active:null,workspaces:[],members:[],workspace:null,dirty:false,saving:false,timer:null,revision:0};
const notify=(m,err=false)=>{const t=$('toast');t.textContent=m;t.className='show'+(err?' error':'');clearTimeout(notify.timer);notify.timer=setTimeout(()=>t.className='',4500)};
const get=id=>$(id).value, nameOf=(arr,id)=>arr.find(x=>x.id===id)?.name||'—';
const option=(v,t)=>`<option value="${esc(v)}">${esc(t)}</option>`;
const safe=s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9_-]+/gi,'_').slice(0,60);
function error(e){notify(e.message||String(e),true);console.error(e)}
function fill(id,rows,placeholder,prev){$(id).innerHTML=option('',placeholder)+rows.map(x=>option(x.id,x.name)).join('');if(rows.some(x=>x.id===prev))$(id).value=prev}
async function q(table,fn){const {data,error}=await fn(state.db.from(table));if(error)throw error;return data||[]}
async function connect(){const cfg=window.AULAEVAL_CONFIG;if(!cfg?.url||!cfg?.key)throw Error('Falta la configuración pública. Revisa las variables de entorno y vuelve a desplegar Netlify.');if(!window.supabase?.createClient)throw Error('No se cargó Supabase JS. Revisa la conexión a Internet.');state.db=supabase.createClient(cfg.url,cfg.key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});const {data,error:e}=await state.db.auth.getUser();if(e&&e.name!=='AuthSessionMissingError')console.warn(e.message);state.user=data?.user||null;$('loginView').classList.toggle('hidden',!!state.user);$('app').classList.toggle('hidden',!state.user);if(state.user)await boot()}
$('forgotPassword').onclick=async()=>{const email=get('email').trim();if(!email){notify('Escribe primero tu correo electrónico.',true);return}try{const {error:e}=await state.db.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});if(e)throw e;notify('Si el correo está registrado, recibirás instrucciones para recuperar tu contraseña.')}catch(e){error(e)}};
$('login').onclick=async()=>{try{const {data,error:e}=await state.db.auth.signInWithPassword({email:get('email').trim(),password:get('password')});if(e)throw e;state.user=data.user;$('loginView').classList.add('hidden');$('app').classList.remove('hidden');try{await boot()}catch(e){$('app').classList.add('hidden');$('loginView').classList.remove('hidden');throw e}}catch(e){error(e)}};
$('signup').onclick=async()=>{try{const {error:e}=await state.db.auth.signUp({email:get('email').trim(),password:get('password')});if(e)throw e;notify('Cuenta solicitada. Revisa tu correo si se requiere confirmación.')}catch(e){error(e)}};
$('logout').onclick=async()=>{if(!await flush())return;await state.db.auth.signOut();location.reload()};
async function boot(){$('userEmail').textContent=state.user.email;await refreshWorkspaces();renderRubric();switchPage('dashboard')}
async function refreshWorkspaces(prefer){const {error:e}=await state.db.rpc('ensure_personal_workspace');if(e)throw e;const [spaces,members]=await Promise.all([q('workspaces',x=>x.select('*').order('created_at')),q('workspace_members',x=>x.select('*'))]);state.workspaces=spaces;state.members=members;const remembered=localStorage.getItem('aulaeval_workspace_'+state.user.id);const desired=prefer||state.workspace||remembered;state.workspace=spaces.some(x=>x.id===desired)?desired:spaces[0]?.id;const sel=$('workspaceSelect');sel.innerHTML=spaces.map(w=>option(w.id,(w.kind==='personal'?'👤 ':'🏫 ')+w.name)).join('');sel.value=state.workspace||'';await reload()}
$('workspaceSelect').onchange=async()=>{if(!await flush()){$('workspaceSelect').value=state.workspace;return}state.workspace=get('workspaceSelect');localStorage.setItem('aulaeval_workspace_'+state.user.id,state.workspace);state.active=null;await reload();loadEval();notify('Espacio de trabajo cambiado')};
$('openWorkspace').onclick=()=>{const w=state.workspaces.find(x=>x.id===state.workspace),admin=state.members.some(m=>m.workspace_id===state.workspace&&m.user_id===state.user.id&&m.role==='admin');const members=state.members.filter(m=>m.workspace_id===state.workspace);modal('Gestionar espacios de trabajo',`<div class="workspace-actions"><button type="button" id="createSchool">+ Crear colegio compartido</button><button type="button" id="joinSchool">Unirme con un código de invitación</button>${w?.kind==='school'&&admin?'<button type="button" id="inviteSchool">Generar invitación para otro docente</button>':''}</div><p class="muted">Espacio actual: ${esc(w?.name)}. Los integrantes de un colegio pueden ver y editar los registros de ese colegio.</p><div class="members">${members.map(m=>`<div>${m.user_id===state.user.id?'Tú':esc(m.user_id.slice(0,8)+'…')} · ${esc(m.role)} ${admin&&m.role!=='admin'?`<button type="button" data-remove-member="${m.user_id}">Quitar</button>`:''}</div>`).join('')}</div>`,async()=>{});$('modalSave').style.display='none';$('modal').addEventListener('close',()=>{$('modalSave').style.display=''}, {once:true});
$('createSchool').onclick=async()=>{const name=prompt('Nombre del colegio:');if(!name)return;try{const {data,error:e}=await state.db.rpc('create_school_workspace',{p_name:name});if(e)throw e;$('modal').close();await refreshWorkspaces(data);notify('Colegio creado')}catch(e){error(e)}};
$('joinSchool').onclick=async()=>{const code=prompt('Pega el código de invitación:');if(!code)return;try{const {data,error:e}=await state.db.rpc('redeem_workspace_invite',{p_token:code});if(e)throw e;$('modal').close();await refreshWorkspaces(data);notify('Te uniste al colegio')}catch(e){error(e)}};
if($('inviteSchool'))$('inviteSchool').onclick=async()=>{try{const {data,error:e}=await state.db.rpc('create_workspace_invite',{p_workspace:state.workspace});if(e)throw e;await navigator.clipboard.writeText(data).catch(()=>{});alert('Código de invitación (válido 7 días, un solo uso). Cópialo y compártelo por un canal privado:\n'+data)}catch(e){error(e)}};
document.querySelectorAll('[data-remove-member]').forEach(b=>b.onclick=async()=>{if(!confirm('¿Quitar a este docente del colegio?'))return;try{const {error:e}=await state.db.rpc('remove_workspace_member',{p_workspace:state.workspace,p_user:b.dataset.removeMember});if(e)throw e;$('modal').close();await refreshWorkspaces();notify('Docente retirado')}catch(e){error(e)}})};

async function reload(){const [students,subjects,periods,enrollments,evaluations]=await Promise.all([
q('students',x=>x.select('*').eq('workspace_id',state.workspace).order('full_name')),
q('subjects',x=>x.select('*').eq('workspace_id',state.workspace).order('name')),
q('periods',x=>x.select('*').eq('workspace_id',state.workspace).order('name')),
q('enrollments',x=>x.select('*').eq('workspace_id',state.workspace)),
q('evaluations',x=>x.select('*').eq('workspace_id',state.workspace))]);
Object.assign(state,{students,subjects,periods,enrollments,evaluations});renderAll()}
function renderAll(){renderStats();renderStudents();renderCatalog();renderFilters();renderReports()}
function renderStats(){const counts=[['Estudiantes',state.students.length],['Asignaturas',state.subjects.length],['Períodos',state.periods.length],['Evaluaciones registradas',state.evaluations.length]];$('stats').innerHTML=counts.map(([k,v])=>`<div class="stat"><span>${esc(k)}</span><b>${v}</b></div>`).join('');$('weightCards').innerHTML=RUBRICS.map(r=>`<div class="weight"><b>${r.items.reduce((a,b)=>a+b[1],0)} pts</b><span>${esc(r.name)}</span></div>`).join('')}
function renderStudents(){const search=get('studentSearch').toLocaleLowerCase('es'),course=get('studentCourseFilter');const courses=[...new Set(state.students.map(x=>x.course))].sort();const old=course;$('studentCourseFilter').innerHTML=option('','Todos los cursos')+courses.map(x=>option(x,x)).join('');$('studentCourseFilter').value=courses.includes(old)?old:'';const rows=state.students.filter(x=>(!course||x.course===course)&&x.full_name.toLocaleLowerCase('es').includes(search));$('studentRows').innerHTML=rows.map(s=>`<tr><td><strong>${esc(s.full_name)}</strong></td><td>${esc(s.course)}</td><td>${esc(state.enrollments.filter(n=>n.student_id===s.id).map(n=>nameOf(state.subjects,n.subject_id)).join(', ')||'Sin asignatura')}</td><td><div class="actions"><button data-editstudent="${s.id}">Editar</button><button data-enroll="${s.id}">Asignaturas</button><button data-delstudent="${s.id}" class="danger-outline">Eliminar</button></div></td></tr>`).join('')||'<tr><td colspan="4">No hay estudiantes en este filtro.</td></tr>'}
$('studentSearch').oninput=renderStudents;$('studentCourseFilter').onchange=renderStudents;
function renderCatalog(){for(const [kind,id,arr] of [['subject','subjectRows',state.subjects],['period','periodRows',state.periods]]){$(id).innerHTML=arr.map(x=>`<div class="catalog-item"><span>${esc(x.name)}</span><div class="actions"><button data-catedit="${kind}:${x.id}">Editar</button><button class="danger-outline" data-catdel="${kind}:${x.id}">Eliminar</button></div></div>`).join('')||'<p class="muted">Aún no hay registros.</p>'}}
function renderFilters(){const ids=['evalSubject','reportSubject'],pids=['evalPeriod','reportPeriod'];ids.forEach(id=>fill(id,state.subjects,'Seleccionar asignatura',get(id)));pids.forEach(id=>fill(id,state.periods,'Seleccionar período',get(id)));renderStudentFilters()}
function eligible(subject,course=''){const ids=new Set(state.enrollments.filter(n=>n.subject_id===subject).map(n=>n.student_id));return state.students.filter(s=>ids.has(s.id)&&(!course||s.course===course))}
function renderStudentFilters(){for(const prefix of ['eval','report']){const subject=get(prefix+'Subject'),courseId=prefix+'Course',studentId=prefix+'Student',oldCourse=get(courseId),oldStudent=get(studentId);const all=eligible(subject);const courses=[...new Set(all.map(s=>s.course))].sort();$(courseId).innerHTML=option('','Todos los cursos')+courses.map(x=>option(x,x)).join('');$(courseId).value=courses.includes(oldCourse)?oldCourse:'';const list=eligible(subject,get(courseId));$(studentId).innerHTML=option('',prefix==='eval'?'Seleccionar estudiante':'Todos los estudiantes')+list.map(s=>option(s.id,s.full_name+' · '+s.course)).join('');if(list.some(s=>s.id===oldStudent))$(studentId).value=oldStudent}}
function switchPage(id){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('hidden',x.id!==id));document.querySelectorAll('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===id));$('pageTitle').textContent=({dashboard:'Resumen general',students:'Gestión de estudiantes',catalog:'Configuración académica',evaluate:'Evaluar estudiantes',reports:'Reportes y resultados'})[id];if(id==='reports')renderReports()}
document.querySelectorAll('#nav button').forEach(b=>b.onclick=async()=>{if(!await flush())return;switchPage(b.dataset.page)});
function modal(title,html,action){$('modalTitle').textContent=title;$('modalContent').innerHTML=html;$('modal').showModal();$('modalForm').onsubmit=async e=>{e.preventDefault();$('modalSave').disabled=true;try{await action();$('modal').close();await reload();notify('Cambios guardados correctamente')}catch(err){error(err)}finally{$('modalSave').disabled=false}}}
$('modalCancel').onclick=()=>$('modal').close();
function inputField(id,label,value=''){return `<label>${esc(label)}<input id="${id}" value="${esc(value)}" required maxlength="200"></label>`}
function subjectChecks(selected){return `<div><strong>Asignaturas del estudiante</strong><div class="catalog-list">${state.subjects.map(x=>`<label style="display:flex;align-items:center;gap:8px"><input type="checkbox" class="subject-check" value="${x.id}" ${selected.includes(x.id)?'checked':''} style="width:auto">${esc(x.name)}</label>`).join('')}</div></div>`}
function chosenSubjects(){return [...document.querySelectorAll('.subject-check:checked')].map(x=>x.value)}
async function updateEnroll(studentId,ids){const old=state.enrollments.filter(x=>x.student_id===studentId);const oldIds=new Set(old.map(x=>x.subject_id));const toAdd=ids.filter(id=>!oldIds.has(id));const toRemove=old.filter(x=>!ids.includes(x.subject_id));for(const x of toRemove){if(state.evaluations.some(e=>e.student_id===studentId&&e.subject_id===x.subject_id))throw Error('No se puede quitar una asignatura con evaluaciones. Elimina primero esas evaluaciones.')}if(toRemove.length){const {error:e}=await state.db.from('enrollments').delete().in('id',toRemove.map(x=>x.id));if(e)throw e}if(toAdd.length){const {error:e}=await state.db.from('enrollments').insert(toAdd.map(subject_id=>({owner_id:state.user.id,workspace_id:state.workspace,student_id:studentId,subject_id})));if(e)throw e}}
$('openImport').onclick=()=>modal('Importar estudiantes',`<label>Curso o grado<input id="importCourse" value="6.º Primaria" required></label><label>Un estudiante por línea<textarea id="importNames" required placeholder="Ana Pérez&#10;Carlos Martínez"></textarea></label>${subjectChecks([])}`,async()=>{const course=get('importCourse').trim(),names=[...new Map(get('importNames').split(/\r?\n/).map(x=>x.trim().replace(/\s+/g,' ')).filter(Boolean).map(n=>[n.toLocaleLowerCase('es'),n])).values()],subs=chosenSubjects();if(!names.length||!course)throw Error('Indica curso y nombres');for(const name of names){let student=state.students.find(s=>s.full_name.toLocaleLowerCase('es')===name.toLocaleLowerCase('es')&&s.course===course);if(!student){const {data,error:e}=await state.db.from('students').insert({owner_id:state.user.id,workspace_id:state.workspace,full_name:name,course,subject:state.subjects.find(s=>s.id===subs[0])?.name||'Sin asignatura'}).select().single();if(e)throw e;student=data}const existing=state.enrollments.filter(x=>x.student_id===student.id).map(x=>x.subject_id);const missing=subs.filter(x=>!existing.includes(x));if(missing.length){const {error:e}=await state.db.from('enrollments').upsert(missing.map(subject_id=>({owner_id:state.user.id,workspace_id:state.workspace,student_id:student.id,subject_id})),{onConflict:'student_id,subject_id'});if(e)throw e}}});
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{
if(b.dataset.editstudent){const s=state.students.find(x=>x.id===b.dataset.editstudent);modal('Editar estudiante',inputField('editName','Nombre completo',s.full_name)+inputField('editCourse','Curso / grado',s.course),async()=>{const {error:e}=await state.db.from('students').update({full_name:get('editName').trim(),course:get('editCourse').trim()}).eq('id',s.id).eq('workspace_id',state.workspace);if(e)throw e})}
if(b.dataset.enroll){const s=state.students.find(x=>x.id===b.dataset.enroll);modal('Asignaturas: '+s.full_name,subjectChecks(state.enrollments.filter(x=>x.student_id===s.id).map(x=>x.subject_id)),async()=>updateEnroll(s.id,chosenSubjects()))}
if(b.dataset.delstudent){const s=state.students.find(x=>x.id===b.dataset.delstudent);if(!confirm('¿Eliminar definitivamente a '+s.full_name+' y TODAS sus calificaciones? Esta acción no se puede deshacer.'))return;const {error:e}=await state.db.from('students').delete().eq('id',s.id).eq('workspace_id',state.workspace);if(e)throw e;await reload();notify('Estudiante eliminado')}
if(b.dataset.catedit){const [kind,id]=b.dataset.catedit.split(':');const table=kind==='subject'?'subjects':'periods',arr=kind==='subject'?state.subjects:state.periods,item=arr.find(x=>x.id===id);modal('Editar '+(kind==='subject'?'asignatura':'período'),inputField('catName','Nombre',item.name),async()=>{const {error:e}=await state.db.from(table).update({name:get('catName').trim()}).eq('id',id).eq('workspace_id',state.workspace);if(e)throw e})}
if(b.dataset.catdel){const [kind,id]=b.dataset.catdel.split(':'),table=kind==='subject'?'subjects':'periods',arr=kind==='subject'?state.subjects:state.periods,item=arr.find(x=>x.id===id);if(state.evaluations.some(e=>kind==='subject'?e.subject_id===id:e.period_id===id))throw Error('No puedes eliminar '+item.name+' porque contiene evaluaciones.');if(!confirm('¿Eliminar '+item.name+'?'))return;const {error:e}=await state.db.from(table).delete().eq('id',id).eq('workspace_id',state.workspace);if(e)throw e;await reload();notify('Registro eliminado')}
}catch(err){error(err)}});
for(const [id,kind] of [['addSubject','subject'],['addPeriod','period']]){$(id).onclick=()=>modal('Nueva '+(kind==='subject'?'asignatura':'etapa evaluativa'),inputField('catName','Nombre'),async()=>{const {error:e}=await state.db.from(kind==='subject'?'subjects':'periods').insert({owner_id:state.user.id,workspace_id:state.workspace,name:get('catName').trim()});if(e)throw e})}
function renderRubric(){$('rubric').innerHTML=RUBRICS.map(r=>`<div class="card"><h3>${esc(r.name)} <span class="muted">${r.items.reduce((a,x)=>a+x[1],0)} pts</span></h3>${r.items.map(([label,max])=>{const i=IND.findIndex(x=>x.id===r.name+'::'+label);return `<div class="indicator"><label for="s${i}">${esc(label)} <span class="muted">· máx. ${max}</span></label><input type="number" id="s${i}" min="0" max="${max}" step="0.25" placeholder="Pendiente"></div>`}).join('')}</div>`).join('');IND.forEach((x,i)=>{$('s'+i).addEventListener('input',()=>{state.dirty=true;recalc();scheduleSave()})});$('notes').addEventListener('input',()=>{state.dirty=true;scheduleSave()})}
function scoresFromForm(){const scores={};for(let i=0;i<IND.length;i++){const x=IND[i],raw=get('s'+i);if(raw===''){scores[x.id]=null;continue}const n=Number(raw);if(!Number.isFinite(n)||n<0||n>x.max||Math.abs(n*4-Math.round(n*4))>1e-8)throw Error('Nota inválida en '+x.label+'. Máximo '+x.max+', incrementos de 0.25.');scores[x.id]=n}return scores}
function totals(scores){const group={};let total=0,done=0;for(const r of RUBRICS){group[r.name]=0;for(const [label] of r.items){const n=scores?.[r.name+'::'+label];if(typeof n==='number'&&Number.isFinite(n)){total+=n;group[r.name]+=n;done++}}}return {group,total,done,complete:done===IND.length}}
function recalc(){let scores={};try{scores=scoresFromForm()}catch(e){$('saveState').textContent='Revisa las notas';return}const t=totals(scores);$('score').innerHTML=`${t.total.toFixed(2).replace(/\.00$/,'')}<span>/100</span>`;$('completion').textContent=`${t.done} de ${IND.length} indicadores · ${t.complete?'Completa':'Pendiente'}`;$('progressBar').style.width=(t.done/IND.length*100)+'%';$('groupTotals').innerHTML=RUBRICS.map(r=>`<div class="group-line"><span>${esc(r.name)}</span><b>${t.group[r.name]} / ${r.items.reduce((a,x)=>a+x[1],0)}</b></div>`).join('')}
function scope(){return {student_id:get('evalStudent'),subject_id:get('evalSubject'),period_id:get('evalPeriod')}}
function record(sc){return state.evaluations.find(e=>e.student_id===sc.student_id&&e.subject_id===sc.subject_id&&e.period_id===sc.period_id)}
function loadEval(){clearTimeout(state.timer);state.dirty=false;state.revision++;const sc=scope();state.active=sc;const ok=Object.values(sc).every(Boolean);$('evalBody').classList.toggle('hidden',!ok);$('evalEmpty').classList.toggle('hidden',ok);if(!ok)return;const row=record(sc);IND.forEach((x,i)=>{$('s'+i).value=typeof row?.scores?.[x.id]==='number'?row.scores[x.id]:''});$('notes').value=row?.notes||'';$('saveState').textContent='Sin cambios';recalc()}
function scheduleSave(){clearTimeout(state.timer);$('saveState').textContent='Cambios sin guardar';state.timer=setTimeout(()=>saveEval(),1100)}
async function saveEval(){if(!state.active||!Object.values(state.active).every(Boolean)||!state.dirty)return true;if(state.saving)return false;const revision=state.revision,sc={...state.active};let scores;try{scores=scoresFromForm()}catch(e){error(e);return false}const notes=get('notes');state.saving=true;$('saveState').textContent='Guardando...';try{const row=record(sc);const payload={owner_id:row?.owner_id||state.user.id,workspace_id:state.workspace,...sc,period:nameOf(state.periods,sc.period_id),scores,notes,updated_at:new Date().toISOString()};let result;if(row)result=await state.db.from('evaluations').update(payload).eq('id',row.id).eq('workspace_id',state.workspace).select().single();else result=await state.db.from('evaluations').insert(payload).select().single();if(result.error)throw result.error;state.evaluations=state.evaluations.filter(e=>e.id!==result.data.id);state.evaluations.push(result.data);if(revision===state.revision){state.dirty=false;$('saveState').textContent='✓ Guardado en línea'}return true}catch(e){error(e);$('saveState').textContent='Error: no guardado';return false}finally{state.saving=false}}
async function flush(){clearTimeout(state.timer);if(state.saving){notify('Espera a que termine el guardado.',true);return false}if(!state.dirty)return true;return await saveEval()}
for(const prefix of ['eval','report']){$(prefix+'Subject').onchange=async()=>{if(prefix==='eval'&&!await flush())return;renderStudentFilters();if(prefix==='eval')loadEval();else renderReports()};$(prefix+'Course').onchange=async()=>{if(prefix==='eval'&&!await flush())return;renderStudentFilters();if(prefix==='eval')loadEval();else renderReports()};$(prefix+'Period').onchange=async()=>{if(prefix==='eval'&&!await flush())return;if(prefix==='eval')loadEval();else renderReports()};$(prefix+'Student').onchange=async()=>{if(prefix==='eval'&&!await flush())return;if(prefix==='eval')loadEval();else renderReports()}}
$('saveNow').onclick=async()=>{if(await saveEval())notify('Evaluación guardada')};
$('nextStudent').onclick=async()=>{if(!await flush())return;const sel=$('evalStudent'),next=sel.selectedIndex+1;if(next<sel.options.length){sel.selectedIndex=next;loadEval()}else notify('Has llegado al último estudiante del filtro.')};
$('clearScores').onclick=async()=>{if(!confirm('¿Borrar todas las puntuaciones y observaciones de esta evaluación?'))return;IND.forEach((x,i)=>$('s'+i).value='');$('notes').value='';state.dirty=true;recalc();await saveEval()};
function reportData(){const sub=get('reportSubject'),period=get('reportPeriod'),course=get('reportCourse'),sid=get('reportStudent');if(!sub||!period)return [];return eligible(sub,course).filter(s=>!sid||s.id===sid).map(s=>{const e=record({student_id:s.id,subject_id:sub,period_id:period});return {s,e,t:totals(e?.scores||{})}})}
function renderReports(){const rows=reportData();$('reportHead').innerHTML='<tr><th>Estudiante</th><th>Curso</th>'+RUBRICS.map(r=>`<th>${esc(r.name)}</th>`).join('')+'<th>Total / 100</th><th>Estado</th></tr>';$('reportRows').innerHTML=rows.map(({s,t})=>`<tr><td><b>${esc(s.full_name)}</b></td><td>${esc(s.course)}</td>${RUBRICS.map(r=>`<td>${t.group[r.name]}</td>`).join('')}<td><b>${t.total}</b></td><td>${t.complete?'Completa':'Pendiente ('+t.done+'/'+IND.length+')'}</td></tr>`).join('')||'<tr><td colspan="11">Selecciona asignatura y período para ver resultados.</td></tr>'}
function requireReports(){if(!get('reportSubject')||!get('reportPeriod'))throw Error('Selecciona asignatura y período');return reportData()}
function generalRows(){return requireReports().map(({s,t,e})=>({'Estudiante':s.full_name,'Curso':s.course,'Asignatura':nameOf(state.subjects,get('reportSubject')),'Período':nameOf(state.periods,get('reportPeriod')),...Object.fromEntries(RUBRICS.map(r=>[r.name,t.group[r.name]])),'Total / 100':t.total,'Estado':t.complete?'Completa':'Pendiente','Indicadores evaluados':t.done+'/'+IND.length,'Observaciones':e?.notes||''}))}
function individual(){const id=get('reportStudent');if(!id)throw Error('Selecciona un estudiante en el filtro de reportes');const row=requireReports().find(x=>x.s.id===id);if(!row)throw Error('No hay estudiante seleccionado');const data=IND.map(x=>({'Rúbrica':x.group,'Indicador':x.label,'Máximo':x.max,'Obtenido':typeof row.e?.scores?.[x.id]==='number'?row.e.scores[x.id]:'Pendiente'}));return {row,data}}
function excel(rows,filename,summary){if(!window.XLSX)throw Error('No se cargó la librería Excel');const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),'Resultados');if(summary)XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(summary),'Resumen');XLSX.writeFile(wb,filename)}
function pdf(title,headers,body,filename,notes){if(!window.jspdf?.jsPDF)throw Error('No se cargó la librería PDF');const d=new jspdf.jsPDF({orientation:headers.length>6?'landscape':'portrait'});d.setFontSize(14);d.text(title,12,16);d.setFontSize(9);d.text(`Asignatura: ${nameOf(state.subjects,get('reportSubject'))} · Período: ${nameOf(state.periods,get('reportPeriod'))}`,12,23);d.autoTable({head:[headers],body,startY:29,margin:9,styles:{fontSize:headers.length>6?6:8,cellPadding:2},theme:'striped'});if(notes){let y=d.lastAutoTable.finalY+10;if(y>d.internal.pageSize.height-25){d.addPage();y=18}d.text(notes,12,y,{maxWidth:d.internal.pageSize.width-24})}d.save(filename)}
function exportAction(fn){return()=>{try{fn()}catch(e){error(e)}}}
$('generalExcel').onclick=exportAction(()=>excel(generalRows(),'evaluaciones_general.xlsx'));
$('generalPDF').onclick=exportAction(()=>{const rows=generalRows(),cols=['Estudiante','Curso',...RUBRICS.map(r=>r.name),'Total / 100','Estado'];pdf('Reporte general',cols,rows.map(r=>cols.map(k=>String(r[k]))),'evaluaciones_general.pdf')});
$('individualExcel').onclick=exportAction(()=>{const {row,data}=individual();excel(data,'evaluacion_'+safe(row.s.full_name)+'.xlsx',[['Estudiante',row.s.full_name],['Curso',row.s.course],['Asignatura',nameOf(state.subjects,get('reportSubject'))],['Período',nameOf(state.periods,get('reportPeriod'))],['Total',row.t.total+'/100'],['Estado',row.t.complete?'Completa':'Pendiente'],['Observaciones',row.e?.notes||'']])});
$('individualPDF').onclick=exportAction(()=>{const {row,data}=individual();pdf('Reporte individual: '+row.s.full_name,['Rúbrica','Indicador','Máximo','Obtenido'],data.map(x=>Object.values(x).map(String)),'evaluacion_'+safe(row.s.full_name)+'.pdf',`Total: ${row.t.total}/100 · ${row.t.complete?'Completa':'Pendiente'}\nObservaciones: ${row.e?.notes||'Sin observaciones'}`)});
window.addEventListener('beforeunload',e=>{if(state.dirty){e.preventDefault();e.returnValue=''}});
(async()=>{try{await connect();state.db.auth.onAuthStateChange(async(event,session)=>{if(event==='PASSWORD_RECOVERY'){setTimeout(async()=>{const pass=prompt('Escribe una nueva contraseña (mínimo 10 caracteres):');if(!pass)return;if(pass.length<10){notify('Contraseña demasiado corta',true);return}const {error:e}=await state.db.auth.updateUser({password:pass});if(e)error(e);else notify('Contraseña actualizada correctamente')},0)}})}catch(e){error(e);$('loginView').classList.remove('hidden');$('loginStatus').textContent='No se pudo iniciar la aplicación: '+e.message;notify('No se pudo iniciar la aplicación: '+e.message,true)}})();
